### ISSUE TITLE
组件商店

### ISSUE THREAD

**Issue by Lock-And-Key** [MrXujiang/h5-Dooring#1]
建设基础能力，开放组件开发权限，开发者可以自主开发所需组件。
组件开发后提审，审批通过后可以在左侧组件商店搜索到，拖拽生成页面。

**Comment by MrXujiang** [comment]
这块可以规划在3.0版本升级中, 目前正在迭代1.1版本, 谢谢反馈, 后期可以多交流

**Comment by armdong** [comment]
很棒的项目，本人目前也在做可视化拖拽这方面的项目，大家可以多多交流。

**Comment by zhangjinlongll** [comment]
> 很棒的项目，本人目前也在做可视化拖拽这方面的项目，大家可以多多交流。

欢迎多提issues 多提好的建议，多多交流
