### ISSUE TITLE
用着用着就卡了

### ISSUE THREAD

**Issue by 532780857** [MrXujiang/h5-Dooring#101]

**Comment by 532780857** [comment]
![image](https://user-images.githubusercontent.com/39074601/117293780-6ce8d580-aea4-11eb-81e1-fcf5e16206ac.png)
是不是死循环了

**Comment by 532780857** [comment]
我就拖动了一点点

**Comment by MrXujiang** [comment]
> 我就拖动了一点点

参考readme的构建运行方案
