### ISSUE TITLE
固定页面

### ISSUE THREAD

**Issue by fangyinghua** [MrXujiang/h5-Dooring#105]
1. 页面路径  /editor
2. 中间页面滚动太快，是否需要滚动？感觉一不小页面被滑走了，能否固定中间页面 。

**Comment by MrXujiang** [comment]
> 1. 页面路径  /editor
> 2. 中间页面滚动太快，是否需要滚动？感觉一不小页面被滑走了，能否固定中间页面 。

可以实现固定, 只要把画布拖拽模式去掉就好了. 谢谢反馈
