### ISSUE TITLE
一刷新报错了

### ISSUE THREAD

**Issue by huanggengzhong** [MrXujiang/h5-Dooring#114]
![image](https://user-images.githubusercontent.com/45531884/128103806-53a9140c-59ca-42f7-889d-fe42b9f1f8d6.png)

**Comment by MrXujiang** [comment]
因为单页面history模式, 可以启动server

**Comment by MrXujiang** [comment]
PC端目前处于按原型阶段, 没对接口, 可以体验H5编辑器
