### ISSUE TITLE
我在编辑页面和预览页面添加pointerEvents: 'none'后，只是操作的时候没有下面的选项了，我们是想编辑和预览的时候就和真实手机环境一样，只在手机屏幕范围内显示而不是铺满整个屏幕或者直接屏蔽掉显示部分。

### ISSUE THREAD

**Issue by hellojxl2016** [MrXujiang/h5-Dooring#119]
please update dooring, or add pointerEvents: 'none' in form compoenent of editor and preview view.
你可以升级版本, 或者在编辑和预览页面的表单组件添加 pointerEvents: 'none', 最新版已经修复了这个问题.

_Originally posted by @MrXujiang in https://github.com/MrXujiang/h5-Dooring/issues/87#issuecomment-761491750_

**Comment by hellojxl2016** [comment]
我在编辑页面和预览页面添加pointerEvents: 'none'后，只是操作的时候没有下面的选项了，我们是想编辑和预览的时候就和真实手机环境一样，只在手机屏幕范围内显示而不是铺满整个屏幕或者直接屏蔽掉显示部分

**Comment by MrXujiang** [comment]
> please update dooring, or add pointerEvents: 'none' in form compoenent of editor and preview view.
> 你可以升级版本, 或者在编辑和预览页面的表单组件添加 pointerEvents: 'none', 最新版已经修复了这个问题.
> 
> _Originally posted by @MrXujiang in [#87 (comment)](https://github.com/MrXujiang/h5-Dooring/issues/87#issuecomment-761491750)_

![image](https://user-images.githubusercontent.com/28833634/131838363-a232ff7d-993b-4add-87b8-df187a90f24e.png)
已优化, 谢谢反馈
