### ISSUE TITLE
编辑和预览的显示宽度范围问题

### ISSUE THREAD

**Issue by hellojxl2016** [MrXujiang/h5-Dooring#120]
我在编辑页面和预览页面添加pointerEvents: 'none'后，只是操作的时候没有下面的选项了，我们是想编辑和预览的时候就和真实手机环境一样，只在手机屏幕范围内显示而不是铺满整个屏幕或者直接屏蔽掉显示部分。

**Comment by MrXujiang** [comment]
![image](https://user-images.githubusercontent.com/28833634/131838219-866ecb79-7478-4dc0-b337-e089c2f70b47.png)
已优化, 谢谢反馈
