### ISSUE TITLE
前端新人有个问题

### ISSUE THREAD

**Issue by biwuyi** [MrXujiang/h5-Dooring#132]
按照readme文档提示，安装完依赖跑起来后到了ui界面，我怎么跳转编辑器页面，我有尝试直接跑package里的editor代码，他提示我丢失remoteEntry.js。请帮帮我

**Comment by MrXujiang** [comment]
> 按照readme文档提示，安装完依赖跑起来后到了ui界面，我怎么跳转编辑器页面，我有尝试直接跑package里的editor代码，他提示我丢失remoteEntry.js。请帮帮我

依赖安装完之后使用lerna来启动

**Comment by MrXujiang** [comment]
> 按照readme文档提示，安装完依赖跑起来后到了ui界面，我怎么跳转编辑器页面，我有尝试直接跑package里的editor代码，他提示我丢失remoteEntry.js。请帮帮我

可以参考readme.md的window无法启动解决方案, 目前提供了无remoteEntry模式的本地启动方案
