### ISSUE TITLE
你好，遇到几个问题，有时间可以帮忙解答下，谢谢

### ISSUE THREAD

**Issue by chenyinkai** [MrXujiang/h5-Dooring#134]
![iShot2021-12-24 13 58 07](https://user-images.githubusercontent.com/22318156/147322675-bc7481af-4480-4104-af85-e3c3c97c3d17.png)
![iShot2021-12-24 13 57 57](https://user-images.githubusercontent.com/22318156/147322686-7d82dc0e-48a0-4125-8309-9a511c8798ac.png)

1.  如图所示，克隆代码后发现类型文件都没有，找不到对应的类型文件
2. 新建表单组件后无法设置默认值
3. 拖拽组件移动顺序时经常报错
![iShot2021-12-24 14 04 37](https://user-images.githubusercontent.com/22318156/147322998-800cb997-3194-410b-88fe-53c2ff9e5995.png)
4. 预览时报错 `URIError: URI malformed`, 且样式未生效

最近在评估类似的 H5 生成库，想要搞一个可以快速部署的应用，当然会购买商业授权版的。麻烦有时间回复下哈，谢谢

**Comment by MrXujiang** [comment]
可以按照readme的安装启动方式运行，亲测没问题，不建议直接yarn start，因为不同项目模式不一样， 以文档为主
