### ISSUE TITLE
有关部分window系统安装启动后无法看到编辑器页面的问题解决方案

### ISSUE THREAD

**Issue by MrXujiang** [MrXujiang/h5-Dooring#136]
目前mac系统下根据readme.md的安装启动方式运行可以正常看到编辑器页面, 但是部分window系统可能无法看到,
可能是由于启动了lerna + webpack5的模块联邦导致的, 可以将ui功能合并到editor下, 注释项目配置中的模块联邦配置即可

**Comment by kkxiaojun** [comment]
![image](https://user-images.githubusercontent.com/20238542/152749164-e1dfd251-4710-4c7e-8c01-4a4c659a5708.png)

这种情况吗

**Comment by mewtwo-git** [comment]
m1 macOS 系统下，启动也只能看到 Page index ......
