### ISSUE TITLE
digital envelope routines::unsupported

### ISSUE THREAD

**Issue by leo-je** [MrXujiang/h5-Dooring#154]
Bundle with webpack 5...
Starting the development server...

● Webpack █████████████████████████ building (10%) 0/2 entries 2/2 dependencies 0/2 modules 2 active 
 babel-loader › src/.umi/umi.ts

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)

**Comment by leo-je** [comment]
done.
export NODE_OPTIONS=--openssl-legacy-provider

**Comment by sgx-wb** [comment]
> NODE_OPTIONS

请问这个是在哪个文件里面添加的，我现在也遇到了同样的问题
![image](https://github.com/MrXujiang/h5-Dooring/assets/96750945/7672741d-0922-4cdb-8e53-5b35f5f15442)
