### ISSUE TITLE
请教一下编辑器目前是不支持内部嵌套吗？

### ISSUE THREAD

**Issue by JoernLee** [MrXujiang/h5-Dooring#26]
你好~最近我也在做可视化编辑器相关的开发工作，我用了下demo，似乎单个组件就是独占一行的布局，那我如果需要实现例如文字左边某个位置有一个居中图标的话应该如何操作呢？目前我考虑的是通过容器内部嵌套or绝对坐标来处理

**Comment by Yezzle** [comment]
grid-layout也可以拖拽resize实现多个组件同行的，我觉要实现你这个功能可以考虑组件本身支持内容样式配置，然后在表单编辑器里面去配置也可以吧

**Comment by MrXujiang** [comment]
嗯嗯, 目前是不建议做嵌套, 主要推荐提供更丰富的组件来避免嵌套代码的兼容性和复杂性问题, 不过再dooring早期版本中使用的react-draggable, 这个是自由拖拽的, 可以支持嵌套, 所以有嵌套需求可以将grid-layout替换为react-draggable, 是完全没问题的

**Comment by JoernLee** [comment]
嗯嗯，感谢你们的建议~的确可以提供一些封装组件，主要是原业务接手前基于6种基本元件封装了上百种组件，有点膨胀了，所以现在想提供一种允许基于Flex布局自由组合元件的组件，后面会综合考虑这两种模式并合并一些相似组件

**Comment by anye931123** [comment]
https://github.com/brick-design/react-visual-editor 我这个是基于自然流设计的，支持组件嵌套
