### ISSUE TITLE
yarn run build && serve ./server  页面报错

### ISSUE THREAD

**Issue by zcg331793187** [MrXujiang/h5-Dooring#28]
![image](https://user-images.githubusercontent.com/13924353/93661536-1ea8d280-fa8b-11ea-9464-1cb071809e04.png)

umi.js:1 Uncaught TypeError: e is not a function
    at umi.js:1
    at Array.map (<anonymous>)
    at umi.js:1
    at u (umi.js:1)
    at an (umi.js:1)
    at Object.d (umi.js:1)
    at Object.c [as start] (umi.js:1)
    at x.render (umi.js:1)
    at nu (umi.js:1)
    at tu (umi.js:1)

yarn run start 正常

**Comment by zcg331793187** [comment]
node version  :v14.10.1
npm version:6.14.8
yarn version :1.3.2

**Comment by MrXujiang** [comment]
> ![image](https://user-images.githubusercontent.com/13924353/93661536-1ea8d280-fa8b-11ea-9464-1cb071809e04.png)
> 
> umi.js:1 Uncaught TypeError: e is not a function
> at umi.js:1
> at Array.map ()
> at umi.js:1
> at u (umi.js:1)
> at an (umi.js:1)
> at Object.d (umi.js:1)
> at Object.c [as start] (umi.js:1)
> at x.render (umi.js:1)
> at nu (umi.js:1)
> at tu (umi.js:1)
> 
> yarn run start 正常

单独执行yarn build， 如果报错，请查看umirc下的输出路径是否存在
单独执行 node server.js, 如果报错， 查看端口号是否被占用

**Comment by zcg331793187** [comment]
> > ![image](https://user-images.githubusercontent.com/13924353/93661536-1ea8d280-fa8b-11ea-9464-1cb071809e04.png)
> > umi.js:1 Uncaught TypeError: e is not a function
> > at umi.js:1
> > at Array.map ()
> > at umi.js:1
> > at u (umi.js:1)
> > at an (umi.js:1)
> > at Object.d (umi.js:1)
> > at Object.c [as start] (umi.js:1)
> > at x.render (umi.js:1)
> > at nu (umi.js:1)
> > at tu (umi.js:1)
> > yarn run start 正常
> 
> 单独执行yarn build， 如果报错，请查看umirc下的输出路径是否存在
> 单独执行 node server.js, 如果报错， 查看端口号是否被占用

均无报错。koa运行正常，能读取到index文件，就是js报错，是否和 yarn lock版本或依赖版本有关

**Comment by yehuozhili** [comment]
> > > ![image](https://user-images.githubusercontent.com/13924353/93661536-1ea8d280-fa8b-11ea-9464-1cb071809e04.png)
> > > umi.js:1 Uncaught TypeError: e is not a function
> > > at umi.js:1
> > > at Array.map ()
> > > at umi.js:1
> > > at u (umi.js:1)
> > > at an (umi.js:1)
> > > at Object.d (umi.js:1)
> > > at Object.c [as start] (umi.js:1)
> > > at x.render (umi.js:1)
> > > at nu (umi.js:1)
> > > at tu (umi.js:1)
> > > yarn run start 正常
> > 
> > 
> > 单独执行yarn build， 如果报错，请查看umirc下的输出路径是否存在
> > 单独执行 node server.js, 如果报错， 查看端口号是否被占用
> 
> 均无报错。koa运行正常，能读取到index文件，就是js报错，是否和 yarn lock版本或依赖版本有关

这个是dva没有判断传入钩子是不是函数造成的，把redux-logger去了就行了
