### ISSUE TITLE
find a new bug

### ISSUE THREAD

**Issue by nickshui** [MrXujiang/h5-Dooring#4]
### 数据源使用，修改一个数据，多个数据被覆盖的问题
这是之前的数据：
![image](https://user-images.githubusercontent.com/43905968/91591999-6eb2de80-e990-11ea-84cc-653f98dfb159.png)
开始修改其中一个数据：
![image](https://user-images.githubusercontent.com/43905968/91592215-c6e9e080-e990-11ea-99b0-cf8168281f8f.png)
修改一个数据保存后，其他数据都被覆盖成这个数据
![image](https://user-images.githubusercontent.com/43905968/91592359-06183180-e991-11ea-8954-6f6a37002bc7.png)

**Comment by MrXujiang** [comment]
已修复
