### ISSUE TITLE
点击下载但未实际下载也会消耗次数

### ISSUE THREAD

**Issue by kill370354** [MrXujiang/h5-Dooring#46]
![image](https://user-images.githubusercontent.com/24654210/95545455-81f5a700-0a30-11eb-867a-a02271241885.png)
每天只能下载一次吗？并且弹出下载框的时候，没有确认下载，也消耗了次数，感觉并不合理。

**Comment by MrXujiang** [comment]
> ![image](https://user-images.githubusercontent.com/24654210/95545455-81f5a700-0a30-11eb-867a-a02271241885.png)
> 每天只能下载一次吗？并且弹出下载框的时候，没有确认下载，也消耗了次数，感觉并不合理。

已修复, have done.
