### ISSUE TITLE
[BUG]主界面支付宝按钮隐藏了

### ISSUE THREAD

**Issue by mengshukeji** [MrXujiang/h5-Dooring#71]
** 问题 **
主界面支付宝二维码的按钮隐藏了

** 重现步骤 **
1. PC edge浏览器打开http://io.nainor.com/h5_plus
2. 即可看到下方按钮展示不全

** 截图 **
![image](https://user-images.githubusercontent.com/61444807/99474023-cad14180-2986-11eb-863c-b78637f96802.png)

**Comment by MrXujiang** [comment]
ok, this bug is fix, you can refresh your page and clear cache to preview. it works to scroll.

**Comment by MrXujiang** [comment]
> ** 问题 **
> 主界面支付宝二维码的按钮隐藏了
> 
> ** 重现步骤 **
> 
> 1. PC edge浏览器打开http://io.nainor.com/h5_plus
> 2. 即可看到下方按钮展示不全
> 
> ** 截图 **
> ![image](https://user-images.githubusercontent.com/61444807/99474023-cad14180-2986-11eb-863c-b78637f96802.png)

已修复, 清空缓存刷新页面即可测试. thanks your issue.
