### ISSUE TITLE
react-draggable 和 react-dnd 是不是两个相同的库,为啥子要使用两个库呢

### ISSUE THREAD

**Issue by chenyangyang123** [MrXujiang/h5-Dooring#80]
左侧组件总览的面板 [ react-dnd ]和 中间主操作区域 [react-draggable] 使用的两个相同功能的拖拽组件,为什么呢?

**Comment by MrXujiang** [comment]
> 左侧组件总览的面板 [ react-dnd ]和 中间主操作区域 [react-draggable] 使用的两个相同功能的拖拽组件,为什么呢?

react-draggable主要是拖拽更灵活方便, 其实用dnd实现也可以, 后期可以考虑合并成一个版本, 如果你有时间欢迎贡献代码~
