### ISSUE TITLE
真机测试按钮bug

### ISSUE THREAD

**Issue by 1247748612** [MrXujiang/h5-Dooring#83]
禁用情况下，依然能点击并弹出二维码
![image](https://user-images.githubusercontent.com/29533304/102974141-04bed600-4539-11eb-83ec-c6c1f830356f.png)

**Comment by 1247748612** [comment]
保存并自动发布 icon button也同样有此问题

**Comment by MrXujiang** [comment]
> 禁用情况下，依然能点击并弹出二维码
> ![image](https://user-images.githubusercontent.com/29533304/102974141-04bed600-4539-11eb-83ec-c6c1f830356f.png)

可以发一个配置的链接, 我调试一下看看

**Comment by MrXujiang** [comment]
已修复
