### ISSUE TITLE
是否支持多页面？

### ISSUE THREAD

**Issue by westudiodev** [MrXujiang/h5-Dooring#85]
有很多场景需要多页面，通过上下滑动切换页面，Dooring目前支持吗？
类似鲁班-H5这样的
https://h5.luban-h5.com/

![Screen Shot 2021-01-02 at 12 55 47](https://user-images.githubusercontent.com/33219803/103451046-eb1c4c00-4cf9-11eb-84dd-2e60c4ac5324.jpg)

**Comment by MrXujiang** [comment]
目前支持H5多页面配置, 但是主要是移动端站点的多页面, 不仅仅是上下滑动~
At present, h5-multi-page configuration is supported, but mainly mobile site multi-page, not just swipe up and down.
h5 dooring is powerful and Sustainable.
