### ISSUE TITLE
制作和预览h5页面时移动端组件铺满整个屏幕

### ISSUE THREAD

**Issue by xuexiaoao** [MrXujiang/h5-Dooring#87]
## 使用表格组件添加表单控件，选择下拉列表后，下拉选择项铺满整个屏幕，预览页面也是同样的问题
> 当前版本是1.3.0

![image](https://user-images.githubusercontent.com/18185523/104566296-67167c80-5688-11eb-8fc1-8f6a60fa4f8f.png)
![image](https://user-images.githubusercontent.com/18185523/104566650-d42a1200-5688-11eb-9a62-f77948533ee7.png)

**Comment by MrXujiang** [comment]
please update dooring, or add pointerEvents: 'none' in form compoenent of editor and preview view.
你可以升级版本, 或者在编辑和预览页面的表单组件添加 pointerEvents: 'none', 最新版已经修复了这个问题.
