### ISSUE TITLE
可不可以底部固定一个按钮

### ISSUE THREAD

**Issue by Zachary-zm** [MrXujiang/h5-Dooring#89]
可不可以底部固定一个按钮  页面滚动按钮位置不变

**Comment by MrXujiang** [comment]
h5-dooring is ok, it will update your needs.

**Comment by MrXujiang** [comment]
> 可不可以底部固定一个按钮 页面滚动按钮位置不变

目前已支持固定组件, 固定头部组件.谢谢反馈
