### ISSUE TITLE
拉取代码后，本地运行报错

### ISSUE THREAD

**Issue by hhm-lxb** [MrXujiang/h5-Dooring#90]
![image](https://user-images.githubusercontent.com/34794050/108630598-92b72e80-74a0-11eb-8b84-87bfcb9d0842.png)
1.拉取代码后，运行了npm run start 和 npm run dev后，请问这是什么原因呢？
2. 另外我还想知道怎么注册会员，我找了很久没找到注册的入口，只有登陆的？因为现在不登陆的话，体验不了。

**Comment by MrXujiang** [comment]
已解决, 请重新拉取代码.

> ![image](https://user-images.githubusercontent.com/34794050/108630598-92b72e80-74a0-11eb-8b84-87bfcb9d0842.png)
> 1.拉取代码后，运行了npm run start 和 npm run dev后，请问这是什么原因呢？
> 2. 另外我还想知道怎么注册会员，我找了很久没找到注册的入口，只有登陆的？因为现在不登陆的话，体验不了。

**Comment by hhm-lxb** [comment]
好的，非常感谢
