### ISSUE TITLE
后续会考虑增加在线扩展代码不

### ISSUE THREAD

**Issue by tanyo520** [MrXujiang/h5-Dooring#91]
一些复杂场景通过扩展代码实现

**Comment by MrXujiang** [comment]
目前已支持按钮, 可视化等组件编辑自定义代码函数, 后续会支持更加强大的自定义组件编辑模式.

> 一些复杂场景通过扩展代码实现

**Comment by MrXujiang** [comment]
> 一些复杂场景通过扩展代码实现

已支持在线自定义组件, 谢谢反馈
