### ISSUE TITLE
你好，能不能实现类似www.mixbook.com 他们一样的编辑器？

### ISSUE THREAD

**Issue by Sabirjan** [MrXujiang/h5-Dooring#99]
你好，能不能实现类似www.mixbook.com 他们一样的编辑器？

**Comment by MrXujiang** [comment]
> www.mixbook.com

完全没问题

**Comment by Sabirjan** [comment]
@MrXujiang 如果可以的话，我想买V6可视化大屏 + H5-Dooring组 版。
但是我看 没有照片书的Demo？

**Comment by Sabirjan** [comment]
有类似的Demo，能不能发一下
